# Generated by Django 3.1.1 on 2021-01-25 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ses_plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
                ('type', models.CharField(max_length=255)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('sent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='django_ses_plus.sentemail')),
            ],
            options={
                'verbose_name': 'Sent Email Attachment',
                'verbose_name_plural': 'Sent Email Attachments',
            },
        ),
    ]
