# Generated by Django 3.1.3 on 2021-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ses_plus', '0002_add_sent_email_attachment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='bounce_sub_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='bounce_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='is_complained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced')], default='unknown', max_length=50),
        ),
    ]
